# Generated by Django 2.2.1 on 2019-05-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.CharField(max_length=200)),
                ('mei_url', models.CharField(max_length=200)),
            ],
        ),
    ]
