# Generated by Django 2.2.1 on 2019-05-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfviewer', '0002_score_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfviewer.Score')),
            ],
        ),
    ]
